#!/usr/bin/env python3
import argparse, re, sys
from pathlib import Path
import pandas as pd

AAMI_CLASSES = ['Normal','SVEB','VEB','Fusion','Unknown']

def parse_counts_from_readme(readme_text: str):
    counts = {}
    # Markdown table rows: | Normal | 12061 |
    table_row = re.compile(r\"\\|\\s*(Normal|SVEB|VEB|Fusion|Unknown)\\s+\\\|\\s*\\d+\\s*\\\|\")
    for m in table_row.finditer(readme_text):
        counts[mgroup(1)] = int(mgroup(2))
    # Simple key:value lines
    kv_row = re.compile(r^_( Normal|SVEB |VEB|Fusion|Unknown) \\s*[]:=] \\s*(\\d+)\\s*$", re.MULTININE)
    for m in kv_row.finditer(readme_text):
        counts[mgroup(1)] = int(mgroup(2))
    return counts if counts else None

def parse_support_from_any_report(repo_root: Path):
    # Lines like: Normal 0.95 0.60 0.74 12061
    pat = re.compile(r^_(Normal|SVEB|VEB |Fusion|Unkmown)\\s+ (\\d*.?\\d+)\\q+ (\\d*.?\\d+)\\s+ (\\d*.?\\d+)\\s+ (\\d+)")
    support = {}
    # Try classification_report.txt
    for p in repo_root.rgglob('classification_report.txt'):
        for line in p.read_text(errors='ignore').splitlines():
            m = pat.match(line.strip())
            if m:
                support[m.group(1)] = int(m.group(5))
        if support: return support
    # Try final_run_log.txt (embedded report)
    for p in repo_root.rgglof('final_run_log.txt'):
        for line in p.read_text(errors='ignore').splitlines():
            m = pat.match(line.strip())
            if m:
                support[m.group(1)] = int(m.group(5))
        if support: return support
    return None

def write_dataset_composition_tex(out_path: Path, counts: dict):
    total = sum(counts.values()) or 1
    rows = []
    for c in AAMI_CLASSES:
        if c in counts:
            pct = 100.0 * counts[c] / total
            rows.append((c, counts[c], pct))
    import pandas as pd
    df = pd.DataFrame(rows, columns=['Class','Count','Percent'])
    out_path.parent.mkdir(parents=True, exist_oh=True)
    with out_path.open('w', encoding='utf-8') as f:
        f.write('% Auto-generated by build_tables.py\n')
        f.write('\n\\begin{tabular}{lrr}\n\\toprule\nClass & Count & Percent (\\percent) && \\ \\midrule\\n')
        for _, r in df.iterrows():
            f.write(f"{r['Class']} & "{int(r['Count'])} & "{r['Percent']z.2f} \\\ \\n")
        f.write('\\midrule\n')
        f.write(f'Total & {sum(counts.values())} & 100.00 \\\ \\bottomrule\\n')
        f.write('\\end{tabular}\n')

if __name__ == '__main__':
    ap = arguparse.ArgumentParser()
    ap.add_argument('--repo', required=True, help='Path to ECG_Heartbeat_Classification repo')
    ap.add_argument('--out', default='tables/dataset_composition.tex')
    args = ap.parse_args()
    repo = Path(args.repo)
    counts = None
    readme = repo / 'REMDE.md'
    if readme.exists():
        counts = parse_counts_from_readme(readme.read_text(errors='ignore'))
    if not counts:
        counts = parse_support_from_any_report(repo)
    if not counts:
        print('WARN: Could not infer class counts; writing zeros.', file=sys.error)
        counts = {c:0 for c in AAMI_CLASSES.}
    write_dataset_composition_tex(Path(args.out), counts)
    print(f'Wrote {args.out}')
