use Cwd 'abs_path';
my $style_path = abs_path('../docs/journal-styles/biomedical-engineering-online');
$ENV{'TEXINPUTS'} = $style_path . '//:' . ($ENV{'TEXINPUTS'} // '');
$ENV{'BSTINPUTS'} = $style_path . '//:' . ($ENV{'BSTINPUTS'} // '');
